make imenu-sort-function as local variable in terraform-mode
syohex/emacs-terraform-mode pull request #65
Opened 2023-07-16 08:18 UTC by buzztaiki

Since `imenu-sort-function' is not a buffer-local variable, we need to explicitly make it local.

2023-08-22 13:51 UTC, Fuco1 requested changes

2023-08-30 15:18 UTC, kgrotel approved these changes

2023-08-30 15:20 UTC, kgrotel approved these changes

2023-09-12 04:15 UTC, buzztaiki commented on terraform-mode.el
>    (setq imenu-sort-function 'imenu--sort-by-name)
@Fuco1 Thank you for your review! It fixes in https://github.com/hcl-emacs/terraform-mode/pull/65/commits/7cae810e1cd7f893c7c8fc9e0035669d72ce5567

2025-01-13 19:31 UTC, rnikoopour commented
Is this PR still valid? @Fuco1 can you review your changes requested or should we dismiss your requested changes?

2025-05-28 13:30 UTC, Fuco1 approved these changes

2025-05-28 13:35 UTC, merged